# Generated by Django 6.0 on 2025-12-25 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=200, unique=True)),
                ('phone_user', models.CharField(max_length=11, unique=True)),
                ('password_user', models.CharField(max_length=200)),
                ('register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('item_image', models.ImageField(upload_to='food-images/')),
                ('item_qauntity', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('item_date', models.DateTimeField(auto_now_add=True)),
                ('catogry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodDelivery.catogery')),
            ],
        ),
    ]
