# Generated by Django 6.0 on 2025-12-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0002_cart_order_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usern',
            new_name='Username',
        ),
    ]
